################################################################################
#   Program Name:     etables.R
#   Author:           Erik Iverson
#   Created:          06/22/2010
#
#   Last saved
#    Time-stamp:      <2010-07-18 21:31:38 erik>
#
#   Purpose:          
#
#   Input:            
#
#   Output:           
#
#   NB:               
#
#   Modfied by:       
#
#   ** Generated by auto-insert on 06/22/2010 at 09:49:47**
################################################################################

load("~/fs/IDCRP-053/output/rdata/pead.bl.Rdata")
form <- hiv ~ age + gender

parseFormula <- function(formula, data) {
  options(na.action = "na.pass")
  mf <- model.frame(formula, data)
  Terms <- terms(formula)
  strat <- attr(Terms, "response")

  if(strat != 0)
    df.vars <- mf[-strat]                 #drop arg?
  else {
    df.vars <- mf
    mf$fake.strat <- gl(1, nrow(mf), labels = "")
    strat <- match("fake.strat", names(mf)) 
  }

  list(vars = df.vars, strat = mf[[strat]])
  
}

etable <- function(x, ...) {
  UseMethod("etable")
}

etable.function <- function(FUNCTION, ...) {
  if(any(c("summary.function",
           "format.function",
           "latex.function",
           "html.function") %in% names(list(...))))
    etable.default(...)
  else
    do.call(FUNCTION, list(...))
}

esummary <- function(x, strat, data, ...) {
  UseMethod("esummary")
}

esummary.default <- function(x, strat, data, ...) {
  quant <- quantile(x, probs = c(.25, .5, .75), ...)
  attr(quant, "N") <- length(x)
  quant
}

esummary.factor <- function(x, strat, data, ...) {
  tbl <- table(x, ...)
  attr(tbl, "N") <- length(x)
  tbl
}

`+.etable` <- function(x, y) {
  if(!is.null(attr(y, "resolve")) && attr(y, "resolve")) {
    if(is.null(y$data))
      y$data <- x$data
    if(is.null(y$formula))
      y$formula <- x$formula
    y <- do.call(etable.formula, y)
  }
  addelement <- function(x, y) {
    if(!is.matrix(y))
      y <- as.matrix(y)
    un <- union(rownames(x), rownames(y))
    xx <- as.data.frame(unclass(as.matrix(x)))
    yy <- as.data.frame(unclass(as.matrix(y)))
    xx$rns <- rownames(x)
    yy$rns <- rownames(y)
    mydf <- merge(xx, yy, by = "rns", all = TRUE)
    mydf <- mydf[match(un, mydf[["rns"]]), ]
    rns <- mydf[["rns"]]
    ret <- as.matrix(mydf[!names(mydf) %in% "rns"])
    rownames(ret) <- rns
    ret
  }
  mapvars <- c("plain", "latex")
  ret <- mapply(addelement, x[mapvars], y[mapvars], SIMPLIFY = FALSE)
  ret$formula <- x$formula
  ret$data <- x$data
  attr(ret, "resolve") <- FALSE
  class(ret) <- c("etable")
  ret
}

## say I want to add statistical test.

etest <- function(x, strat, data, ...) {
  UseMethod("etest")
}

etest.default <- function(x, strat, data, round.digits = 2, ...) {
  round(t.test(x ~ strat, ...)$p.value, round.digits)
}

etest.factor <- function(x, strat, data, round.digits = 2, ...) {
  round(fisher.test(x, strat, ...)$p.value, round.digits)
}

## now how about the regression coefficient?

elm <- function(x, strat, data, ...) {
 UseMethod("elm")
}

elm.default <- function(x, strat, data, model.formula, round.digits = 2, ...) {
  data$x <- x
  round(coef(lm(update(model.formula, diffs ~ .), data = data), ...)[2], round.digits)
}

elm.factor <- function(x, strat, data, model.formula, round.digits = 2, ...) {
  data$x <- x
  round(exp(coef(glm(update(model.formula, inc4x ~ .),
                     data = data, family = binomial, ...))[2]), round.digits)
}

elm2 <- function(formula, data, round.digits = 2, ...) {
  ret <- round(coef(lm(formula, data, ...))[-1], round.digits)
  list(plain = ret, latex = ret)
}


etable.default <- function(x, ...) {
  if(!"data" %in% names(list(...)))
    lst <- c(list(formula = NULL, data = NULL), list(...))
  else
    lst <- c(list(formula = NULL), list(...))
  attr(lst, "resolve") <- TRUE
  lst
}

ehtml <- function(x, ...) {
  x
}

etable.formula <- function(formula, data,
                           summary.function = esummary,
                           format.function = eformat,
                           latex.function = elatex,
                           html.function = ehtml, 
                           colname, ...) {

  if(missing(data)) {
    lst <- as.list(match.call()[-1])
    attr(lst, "resolve") <- TRUE
    return(lst)
  }

  dfv <- parseFormula(formula, data)
  table.vars <- strsplit(tail(as.character(formula), n = 1), " + ", fixed = TRUE)[[1]]

  xx <- NULL
  for(x in table.vars) {
      if(is.numeric(data[[x]])) {
        y <- x
      }
      if(is.factor(data[[x]])) {
        y <- c(x, paste(x, names(table(data[[x]])), sep = ""))
      }
      xx <- c(xx, y)
  }
  
  ret <- lapply(dfv$vars, summary.function, dfv$strat, data, ...)

  format.ret <- NULL
  for(i in 1:length(ret)) {
    val <- format.function(ret[[i]], names(ret)[i], data)
    format.ret <- c(format.ret, val)
  }
  format.ret <- as.matrix(format.ret[xx], ncol = 1)

  latex.ret <- NULL
  for(i in 1:length(ret)) {
    val <- latex.function(ret[[i]], names(ret)[i], data)
    latex.ret <- c(latex.ret, val)
  }
  latex.ret <- as.matrix(latex.ret[xx], ncol = 1)

  ## set the names of the matrix for printing 
  rownames(format.ret) <- xx
  rownames(latex.ret) <- xx
  if(!missing(colname))
    colnames(format.ret) <- colname

  ## set up the return value (a list)
  return.list <- list(plain = format.ret, latex = latex.ret,
                      formula = formula, data = data)
  attr(return.list, "resolve") <- FALSE
  class(return.list) <- c("etable")
  return.list
}

eformat <- function(x, name, data, ... ) {
  UseMethod("eformat")
}

eformat.default <- function(x, name, data, round.digits = 2, ... ) {
  val <- paste(x, collapse = "/")
  names(val) <- name
  val
}

eformat.table <- function(x, name, data, round.digits = 0, ...) {
  dft <- as.data.frame(x)
  pct <- paste(round(x / sum(x) * 100, round.digits), "%", sep = "")
  val <- paste(pct, paste(dft[["Freq"]], "/", sum(x), sep = ""))
  names(val) <- paste(name, names(x), sep = "")
  val
}


print.etable <- function(x, quote = FALSE, na.print = "--", print.rownames = FALSE, ...) {
  x <- x[["plain"]]
  if(!print.rownames)
    rownames(x) <- NULL
  print.default(unclass(x), quote = quote, na.print = na.print, ...)
}


elatex <- function(x, ...) {
  UseMethod("elatex")
}

elatex.default <- function(x, name, data, ...) {
  ret <- paste("\\scriptsize{", x[1], "}", 
               x[2],
               "\\scriptsize{", x[3], "}",
               sep = " ")
  names(ret) <- name
  ret
}

elatex.table <- function(x, name, data, round.digits, ...) {
  dft <- as.data.frame(x)
  pct <- paste(round(x / sum(x) * 100, round.digits), "\\%", sep = "")
  val <- paste(pct, paste(dft[["Freq"]], "/", sum(x), sep = ""))
  names(val) <- paste(name, names(x), sep = "")
  val
}

eprintidentity <- function(x, name, data, ...) {
  ret <- x
  names(ret) <- name
  ret
}

erownames <- function(x, ...) {
  UseMethod("erownames")
}

erownames.default <- function(x, ...) {
  label(x)
}

erownames.factor <- function(x, ...) {
  ret <- c(label(x), levels(x))
  class(ret) <- "special"
  ret
}

eprintrownames <- function(x, ...) {
  UseMethod("eprintrownames")
}

eprintrownames.character <- eprintidentity

eprintrownames.special <- function(x, name, data, ...) {
  ret <- c(x[1], paste("", tail(x, length(x) - 1)))
  names(ret) <- c(name, paste(name,  levels(data[[name]]), sep = ""))
  ret
}

elatexrownames <- function(x, ...) {
  UseMethod("elatexrownames")
}


elatexrownames.character <- eprintidentity

elatexrownames.special <- function(x, name, data, ...) {
  ret <- c(x[1], paste("~~~", tail(x, length(x) - 1)))
  names(ret) <- c(name, paste(name,  levels(data[[name]]), sep = ""))
  ret
}

latex.etable <- function(x, na.print = "", file = "", headerFunction = eLaTeXHeader,
                         footerFunction = eLaTeXFooter, caption = "", ...) {
  x <- x$latex
  x[is.na(x)] <- na.print
  cat(paste(headerFunction(x, caption, ...), collapse = "\n"), "\n", file = file)
  cat(paste(apply(x, 1, paste, collapse = "&"), collapse = "\\\\\n"), "\\\\\n", file = file,
      append = TRUE)
  cat(paste(footerFunction(x), collapse = "\n"), "\n", file = file, append = TRUE)

}

eLaTeXHeader <- function(x, caption, collabel.just) {
  if(missing(collabel.just))
    collabel.just <- paste(c("l", rep("c", ncol(x) - 1)), collapse = "")
  c(paste("\\begin{longtable}{", collabel.just, "}"),
    paste("\\caption{", caption, "}\\\\"),
    "\\hline\\hline",
    c(paste("\\multicolumn{1}{c}{", colnames(x), "}", collapse = "&"), "\\\\"),
    "\\hline",
    "\\endhead",
    "\\hline")
}

eLaTeXFooter <- function(x) {
  c("\\hline",
    "\\end{longtable}")
}

tmp <- etable(form, data = pead.bl, colname = "rownames",
              summary.function = erownames,
              format.function = eprintrownames,
              latex.function = elatexrownames) +
  etable(form, data = pead.bl, colname = "combined") +
  etable(form, data = subset(pead.bl, hiv == "Positive")) +
  etable(form, data = subset(pead.bl, hiv == "Negative")) +
  etable(hiv ~ age + gender, data = pead.bl,
         summary.function = etest,
         latex.function = eprintidentity) +
 etable(hiv ~ age + gender, data = pead.bl, summary.function = elm,
         model.formula = ~ x + hiv + bmi,
         latex.function = eprintidentity) +
  etable(elm2, update(form, diffs ~ .), data = pead.bl)


etable(form, data = pead.bl, colname = "rownames",
       summary.function = erownames,
       format.function = eprintrownames,
       latex.function = elatexrownames) +
  etable(colname = "combined") +
  etable(data = subset(pead.bl, hiv == "Positive")) +
  etable(data = subset(pead.bl, hiv == "Negative")) +
  etable(summary.function = etest,
         latex.function = eprintidentity) +
  etable(elm2, update(form, diffs ~ .), data = pead.bl)

latex(tmp)

latex(summary(hiv ~ age + gender, data = pead.bl, method = "reverse"), longtable = TRUE)
      



