
* mutable
The mutable package provides a flexible method for generating markup
tables from the R programming language.  It allows users to construct
objects representing arbitrary tabular material and output the object
into a variety of formats. LaTeX, HTML, and plain text output
functions are included by default.

Users can supply their own formatting functions for these output
types, and easily create their own.  For example, the provided LaTeX
output style for factors (percentage and fraction) can be completely
changed if the user specifies their own muExportLatex function. The
modular design of the package allows every markup decision to be
overridden easily and consistently. The result is that the user is in
complete control over the final markup produced, and that multiple
versions of the same table can easily be produced from the same data
simultaneously.

* Installation

* Introduction 

* Examples
Load the data
: load(url('http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/support.sav'))

Give unlabeled variables appropriate labels
: label(support$sex) <- "Gender"
: label(support$income) <- "Income"

Use a high-level mutable function to create a complete table, by default in plain text, LaTeX, and HTML formats
: m1 <- mutableStrat(dzclass ~ age + sex + income, data = support)

Print the table in the running R session
: m1 

Write out HTML file, which uses MathJax by default, and note all
rows/columns/cells are uniquely identified for CSS customization!
:html(m1, completeDocument = TRUE, file = "mutable.html")

The resulting table will contain the following information
| Variable   | N    | ARF/MOSF         | COPD/CHF/Cirrhosis | Coma              | Cancer            | Overall         |
| Age        | 1000 | 47.7/63.66/73.53 | 57.4/67.1/76.24    | 48.63/64.93/77.76 | 53.59/62.64/69.38 | 51.81/64.9/74.5 |
| Gender     | 1000 | --               | --                 | --                | --                | --              |
| female     | --   | 47% 224/477      | 41% 128/314        | 45% 27/60         | 40% 59/149        | 44% 438/1000    |
| male       | --   | 53% 253/477      | 59% 186/314        | 55% 33/60         | 60% 90/149        | 56% 562/1000    |
| Income     | 651  | --               | --                 | --                | --                | --              |
| under $11k | --   | 48% 141/295      | 56% 122/217        | 42% 17/40         | 29% 29/99         | 47% 309/651     |
| $11-$25k   | --   | 22% 66/295       | 26% 56/217         | 32% 13/40         | 26% 26/99         | 25% 161/651     |
| $25-$50k   | --   | 19% 57/295       | 9% 19/217          | 15% 6/40          | 24% 24/99         | 16% 106/651     |
| >$50k      | --   | 11% 31/295       | 9% 20/217          | 10% 4/40          | 20% 20/99         | 12% 75/651      |

     
 
 
 
 
 
 
 
 
 



