################################################################################
##   Program Name:     tcrug.R
##   Author:           
##   Created:          06/18/2012
##
##   Last saved
##    Time-stamp:      <2012-06-18 14:00:11 eiverson>
##
##   Purpose:          mutable demo for TCRUG 
##   ** Generated by auto-insert on 06/18/2012 at 10:00:13**
################################################################################

## NB: setwd() to this directory (location of tcrug.R)
library(Hmisc)
library(xtable)
library(ggplot2)
library(grid)

## define example data.frame for this talk 
set.seed(22)
df1 <- data.frame(strat = sample(c("Group 1", "Group 2"), 100, replace = TRUE),
                  age = rnorm(100, c(50, 40), sd = 10),
                  gender = sample(c("Male", "Female"), 100, replace = TRUE),
                  diffs = rnorm(100, 500, sd = 100),
                  inc4x = sample(c("Yes", "No"), 100, replace = TRUE),
                  bmi = rnorm(100, 30, sd = 2))

label(df1$hiv)    <- "Treatment Group"
label(df1$age)    <- "Age"
label(df1$gender) <- "Gender"
label(df1$diffs)  <- "V2 GMT - V1 GMT"
label(df1$inc4x)  <- "V1/V2 >= 4"
label(df1$bmi)    <- "BMI"


## use Hmisc to generate the table 
form <-  strat ~ age + gender + diffs + inc4x + bmi
sf1 <- summary(form, data = df1, method = "reverse")

sf1

## generate latex representation of the table
latex(sf1, file = "")                   #file = "" writes to screen

l1 <- latex(sf1, file = "hmisc-table1.tex")

## update label with LaTeX math syntax 
label(df1$inc4x)  <- "$\\frac{V1 GMT}{V2 GMT} >= 4$"


## mutable example 
tab1 <- mutable(form, data = df1, colname = "",
                summary.function = muRownames,
                markup.list =
                list(plain = muExportPlain,
                     html  = muExportHTML,
                     latex = muExportLatex))

class(tab1)
str(tab1)

tab1

## let's add another column, unresolved arguments are inherited from tab1 
tab2 <- tab1 + mutable(summary.function = muStratSummary,
                       colname = "Combined Groups")

tab2
tab2$latex

## add column with p-values from statistical test
tab3 <- tab2 + mutable(summary.function = muStratTest,
                       colname = "P-value")

tab3

latex(tab3, file = "mutable-table1.tex")

tab4 <- mutableStrat(form, df1, firstcol = "Variable")
latex(tab4, file = "mutable-table1.tex")


## try changing the summary function

muTCRUG <- function(x, stratVariable, data, ...) {
  y <- runif(2, max = 10)
  class(y) <- "muTCRUG"
  y
}

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")
tab5


muExportPlain.muTCRUG <- function(x, name, data, round.digits = 2, ...) {
  x <- round(x, round.digits)
  val <- paste(round(x[1], round.digits), "Hi from our new output function",
               round(x[2], round.digits))
  names(val) <- name
  val
}

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")
tab5


## what about html?
html(tab5, file = "html/tcrug.html", completeDocument = TRUE,
     cssFile = "main.css")

muExportHTML.muTCRUG <- function(x, name, data, colname, ...) {
  ret <- paste("<td>", muExportPlain(x, name, data, ...),
             "</td>", collapse = "")
  names(ret) <- name
  ret 
}

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")

html(tab5, file = "html/tcrug.html", completeDocument = TRUE,
     cssFile = "main.css")
tab6 <- tab5 + mutable(muglmCoef, form, data = df1, colname = "Odds Ratio")

html(tab6, file = "html/tcrug.html", completeDocument = TRUE,
     cssFile = "main.css")

