################################################################################
##   Program Name:     tcrug.R
##   Author:           
##   Created:          06/18/2012
##
##   Last saved
##    Time-stamp:      <2012-06-18 17:09:18 erik>
##
##   Purpose:          mutable demo for TCRUG 
##   ** Generated by auto-insert on 06/17/2012 at 22:00:13**
################################################################################

################################################################################
## NB: setwd() TO THIS DIRECTORY (LOCATION OF TCRUG.R) BEFORE SOURCING 

library(Hmisc)
library(xtable)
library(ggplot2)
library(grid)

##
################################################################################


################################################################################
## define sample data.frame for our examples 

set.seed(22)
df1 <- data.frame(strat = sample(c("Group 1", "Group 2"), 100, replace = TRUE),
                  age = rnorm(100, c(50, 40), sd = 10),
                  gender = sample(c("Male", "Female"), 100, replace = TRUE),
                  diffs = rnorm(100, 500, sd = 100),
                  inc4x = sample(c("Yes", "No"), 100, replace = TRUE),
                  bmi = rnorm(100, 30, sd = 2))

label(df1$strat)  <- "Treatment Group"
label(df1$age)    <- "Age"
label(df1$gender) <- "Gender"
label(df1$diffs)  <- "V2 Measure - V1 Measure"
label(df1$inc4x)  <- "V1/V2 >= 4"
label(df1$bmi)    <- "BMI"

##
################################################################################


################################################################################
## use Hmisc's summary.formula to generate the table 

form <-  strat ~ age + gender + diffs + inc4x + bmi
sf1 <- summary(form, data = df1, method = "reverse")

sf1

##
################################################################################

################################################################################
## generate latex representation of the table from summary.formula

latex(sf1, file = "")                  

l1 <- latex(sf1, file = "hmisc-table1.tex")

##
################################################################################


################################################################################
## update label with LaTeX math syntax for mutable

label(df1$inc4x)  <- "$$\\frac{V1 Measure}{V2 Measure} >= 4$$"

##
################################################################################

################################################################################
## basic mutable call

tab1 <- mutable(form, data = df1, colname = "",
                summary.function = muRownames,
                markup.list =
                list(plain = muExportPlain,
                     html  = muExportHTML,
                     latex = muExportLatex))

tab1

class(tab1)
str(tab1)

##
################################################################################

################################################################################
## let's add another column, unresolved arguments are inherited from tab1 

tab2 <- tab1 + mutable(summary.function = muStratSummary,
                       colname = "Combined Groups")

tab2
tab2$latex

##
################################################################################

################################################################################
## add column with p-values from statistical test

tab3 <- tab2 + mutable(summary.function = muStratTest,
                       colname = "P-value")

tab3
latex(tab3, file = "mutable-table1.tex")

##
################################################################################


################################################################################
## use a higher-level function to generate common table type

tab4 <- mutableStrat(form, df1, firstcol = "Variable")
latex(tab4, file = "mutable-table1.tex")

##
################################################################################


################################################################################
## try our own summary function

muTCRUG <- function(x, stratVariable, data, ...) {
  y <- runif(2, max = 10)
  class(y) <- "muTCRUG"
  y
}

##
################################################################################

################################################################################
## use the function we defined above 

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")
tab5

##
################################################################################

################################################################################
## want to customize output for columns using that summary function
## let's customize plain text output first 

muExportPlain.muTCRUG <- function(x, name, data, round.digits = 2, ...) {
  x <- round(x, round.digits)
  val <- paste(round(x[1], round.digits), "Hi from our new output function",
               round(x[2], round.digits))
  names(val) <- name
  val
}

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")
tab5

##
################################################################################


################################################################################
## what about html? mathjax output

html(tab5, file = "html/tcrug.html", completeDocument = TRUE)

##
################################################################################

################################################################################
## oops, need to customize the HTML output too, support can be improved 

muExportHTML.muTCRUG <- function(x, name, data, colname, ...) {
  ret <- paste("<td>", muExportPlain(x, name, data, ...),
             "</td>", collapse = "")
  names(ret) <- name
  ret 
}

tab5 <- tab3 + mutable(summary.function = muTCRUG,
                       colname = "TCRUG")

html(tab5, file = "html/tcrug.html", completeDocument = TRUE)

##
################################################################################


################################################################################
## we also have a mutable method for our own functions, requires knowledge
## of internal naming structure 

tab6 <- tab5 + mutable(muglmCoef, form, data = df1, colname = "Odds Ratio (CI)")

html(tab6, file = "html/tcrug.html", completeDocument = TRUE,
     cssFile = "main.css")


##
################################################################################

################################################################################
## can (hopefully easily) manipulate the markup objects directly

str(tab6$html)

## re-order columns, example of ease of operating on final markup object
tab6$html <- tab6$html[,c(1, 5:2)]

html(tab6, file = "html/tcrug.html", completeDocument = TRUE)

##
################################################################################

################################################################################
## use CSS to further customize

html(tab6, file = "html/tcrug.html", completeDocument = TRUE,
     cssFile = "main.css")

##
################################################################################

################################################################################
## TODO:

## coherent treatment of rounding and footnotes
## more advanced CSS, javascript, d3, ... export generics
## other types of markup? markdown? 
## store export functions in their own environment/packages?
## test cases
## could knitr call the right markup extractor? hook functions?

## currently, 'data' argument is passed around all over the place and
## is stored as part of the mutable object, is this wise? certainly
## can't be in all cases... 

##
################################################################################
