################################################################################
#   Program Name:     etables.R
#   Author:           Erik Iverson
#   Created:          06/22/2010
#
#   Last saved
#    Time-stamp:      <2010-09-02 10:32:15 eriki>
#
#   Purpose:          
#
#   Input:            
#
#   Output:           
#
#   NB:               
#
#   Modfied by:       
#
#   ** Generated by auto-insert on 06/22/2010 at 09:49:47**
################################################################################

library(Hmisc)

pead.bl <- data.frame(hiv = sample(c("Positive", "Negative"), 100, replace = TRUE),
                      age = rnorm(100, 50, sd = 5),
                      gender = sample(c("Male", "Female"), 100, replace = TRUE),
                      diffs = rnorm(100, 500, sd = 100),
                      inc4x = sample(c("Yes", "No"), 100, replace = TRUE),
                      bmi = rnorm(100, 30, sd = 3))

label(pead.bl$hiv) <- "HIV Status"
label(pead.bl$age) <- "Age"
label(pead.bl$gender) <- "Gender"
                        
form <- hiv ~ age + gender

parseFormula <- function(formula, data, subset) {
  ## why this option is set?  do we need it, or leave it up to user? 
  options(na.action = "na.pass")

  ## copied from lm, check what it does.
  mf <- match.call(expand.dots = FALSE)
  m <- match(c("formula", "data", "subset"), names(mf), 0L)
  mf <- mf[c(1L, m)]
  mf[[1L]] <- as.name("model.frame")
  mf <- eval(mf, parent.frame())

  Terms <- terms(formula)
  strat <- attr(Terms, "response")

  if(strat != 0)
    df.vars <- mf[-strat]                 #drop arg?
  else {
    df.vars <- mf
    mf$fake.strat <- gl(1, nrow(mf), labels = "")
    strat <- match("fake.strat", names(mf)) 
  }

  list(vars = df.vars, strat = mf[[strat]])
}

etable <- function(x, ...) {
  if(missing(x))
    x <- NULL 
  UseMethod("etable", x)
}

etable.function <- function(FUNCTION, ...) {
  do.call(FUNCTION, list(...))
}

esummary <- function(x, strat, data, ...) {
  UseMethod("esummary")
}
 
esummary.default <- function(x, strat, data, ...) {
  quant <- quantile(x, probs = c(.25, .5, .75), ...)
  attr(quant, "N") <- length(x)
  quant
}

esummary.factor <- function(x, strat, data, ...) {
  tbl <- table(x, ...)
  attr(tbl, "N") <- length(x)
  tbl
}

`+.etable` <- function(x, y) {
  if(!is.null(attr(y, "resolve")) && attr(y, "resolve")) {
    if(is.null(y$data))
      y$data <- x$data
    if(is.symbol(y$data))
      y$data <- eval(y$data)
    if(is.null(y$formula))
      y$formula <- x$formula
    if("subset" %in% names(y)) {
      y$data <- y$data[eval(y$subset, y$data),]
      y$subset <- NULL
    }
    y <- do.call(etable.formula, y)
  }
  addelement <- function(x, y) {
    if(!is.matrix(y))
      y <- as.matrix(y)
    un <- union(rownames(x), rownames(y))
    xx <- as.data.frame(unclass(as.matrix(x)))
    yy <- as.data.frame(unclass(as.matrix(y)))
    xx$rns <- rownames(x)
    yy$rns <- rownames(y)
    mydf <- merge(xx, yy, by = "rns", all = TRUE)
    mydf <- mydf[match(un, mydf[["rns"]]), ]
    rns <- mydf[["rns"]]
    ret <- as.matrix(mydf[!names(mydf) %in% "rns"])
    rownames(ret) <- rns
    ret
  }
  mapvars <- c("plain", "latex")
  ret <- mapply(addelement, x[mapvars], y[mapvars], SIMPLIFY = FALSE)
  ret$formula <- x$formula
  ret$data <- x$data
  attr(ret, "resolve") <- FALSE
  class(ret) <- c("etable")
  ret
}

etest <- function(x, strat, data, ...) {
  UseMethod("etest")
}

etest.default <- function(x, strat, data, round.digits = 2, ...) {
  round(t.test(x ~ strat, ...)$p.value, round.digits)
}

etest.factor <- function(x, strat, data, round.digits = 2, ...) {
  round(chisq.test(x, strat, ...)$p.value, round.digits)
}

elm <- function(formula, data, round.digits = 2, ...) {
  ret <- round(coef(lm(formula, data, ...))[-1], round.digits)
  list(plain = ret, latex = ret)
}


etable.default <- function(x, ...) {
  m <- as.list(match.call())[-1]
  if(!"data" %in% names(m))
    lst <- c(list(formula = NULL, data = NULL), m)
  else
    lst <- c(list(formula = NULL), m)
  attr(lst, "resolve") <- TRUE
  lst
}

ehtml <- function(x, ...) {
  x
}

etable.formula <- function(formula, data,
                           summary.function = esummary,
                           format.function = eformat,
                           latex.function = elatex,
                           html.function = ehtml, 
                           colname,
                           subset = NULL, ...) {

  ## if there was no data argument, we have to go find it first return
  ## from function knowing this, and resolve the data argument later,
  ## since we know `+.etable.` must have been called. 
  
  if(missing(data)) {
    lst <- as.list(match.call()[-1])
    attr(lst, "resolve") <- TRUE
    return(lst)
  }

  m  <- as.list(match.call())[-1]
  if("subset" %in% names(m))
    pfargs <- list(m$formula, m$data, m$subset)
  else
    pfargs <- list(m$formula, m$data, NULL)
  pfargs[sapply(pfargs, is.null)] <- NULL
  dfv <- do.call(parseFormula, pfargs)
  table.vars <- strsplit(tail(as.character(formula), n = 1), " + ", fixed = TRUE)[[1]]

  xx <- NULL
  for(x in table.vars) {
      if(is.numeric(data[[x]])) {
        y <- x
      }
      if(is.factor(data[[x]])) {
        y <- c(x, paste(x, names(table(data[[x]])), sep = ""))
      }
      xx <- c(xx, y)
  }
  
  ret <- lapply(dfv$vars, summary.function, dfv$strat, data, ...)

  ## grab any defaults for formatting functions from the
  ## summary.function attributes we need to know which ones to grab
  ## though, probably through a list as as argument to this function.
  ## Or, we could just define any of them based on the attribute being
  ## present.  But how would we know which functions are actually
  ## meant to be called?  Perhaps intitial object can specify these.
  ## for now, just use our latex/html/format

  if(!is.null(lf <- attr(summary.function, "latex.function")))
    latex.function <- lf
  if(!is.null(hf <- attr(summary.function, "html.function")))
    html.function <- hf
  if(!is.null(ff <- attr(summary.function, "format.function")))
    format.function <- ff
  
  format.ret <- NULL
  for(i in 1:length(ret)) {
    val <- format.function(ret[[i]], names(ret)[i], data)
    format.ret <- c(format.ret, val)
  }
  format.ret <- as.matrix(format.ret[xx], ncol = 1)

  latex.ret <- NULL
  for(i in 1:length(ret)) {
    val <- latex.function(ret[[i]], names(ret)[i], data)
    latex.ret <- c(latex.ret, val)
  }
  latex.ret <- as.matrix(latex.ret[xx], ncol = 1)

  ## set the names of the matrix for printing 
  rownames(format.ret) <- xx
  rownames(latex.ret) <- xx
  if(!missing(colname)) {
    colnames(format.ret) <- colname
    colnames(latex.ret) <- colname
  }

  ## set up the return value (a list)
  return.list <- list(plain = format.ret, latex = latex.ret,
                      formula = formula, data = data)
  attr(return.list, "resolve") <- FALSE
  class(return.list) <- c("etable")
  return.list
}

eformat <- function(x, name, data, ... ) {
  UseMethod("eformat")
}

eformat.default <- function(x, name, data, round.digits = 2, ... ) {
  val <- paste(round(x, round.digits), collapse = "/")
  names(val) <- name
  val
}

eformat.table <- function(x, name, data, round.digits = 0, ...) {
  dft <- as.data.frame(x)
  pct <- paste(round(x / sum(x) * 100, round.digits), "%", sep = "")
  val <- paste(pct, paste(dft[["Freq"]], "/", sum(x), sep = ""))
  names(val) <- paste(name, names(x), sep = "")
  val
}

print.etable <- function(x, quote = FALSE, na.print = "--", print.rownames = FALSE, ...) {
  x <- x[["plain"]]
  if(!print.rownames)
    rownames(x) <- NULL
  print.default(unclass(x), quote = quote, na.print = na.print, ...)
}


elatex <- function(x, ...) {
  UseMethod("elatex")
}

elatex.default <- function(x, name, data, round.digits = 1, ...) {
  ret <- paste(round(x[1], round.digits), "/", 
               round(x[2], round.digits), "/",
               round(x[3], round.digits),
               sep = " ")
  names(ret) <- name
  ret
}

elatex.table <- function(x, name, data, round.digits, ...) {
  dft <- as.data.frame(x)
  pct <- paste(round(x / sum(x) * 100, round.digits), "\\%", sep = "")
  val <- paste(pct, paste(dft[["Freq"]], "/", sum(x), sep = ""))
  names(val) <- paste(name, names(x), sep = "")
  val
}

eprintidentity <- function(x, name, data, ...) {
  ret <- x
  names(ret) <- name
  ret
}

erownames <- function(x, ...) {
  UseMethod("erownames")
}

erownames.default <- function(x, ...) {
  label(x)
}

erownames.factor <- function(x, ...) {
  ret <- c(label(x), levels(x))
  class(ret) <- "special"
  ret
}

eprintrownames <- function(x, ...) {
  UseMethod("eprintrownames")
}

eprintrownames.character <- eprintidentity

eprintrownames.special <- function(x, name, data, ...) {
  ret <- c(x[1], paste("", tail(x, length(x) - 1)))
  names(ret) <- c(name, paste(name,  levels(data[[name]]), sep = ""))
  ret
}

elatexrownames <- function(x, ...) {
  UseMethod("elatexrownames")
}


elatexrownames.character <- eprintidentity

elatexrownames.special <- function(x, name, data, ...) {
  ret <- c(x[1], paste("~~~", tail(x, length(x) - 1)))
  names(ret) <- c(name, paste(name,  levels(data[[name]]), sep = ""))
  ret
}

latex.etable <- function(x, na.print = "", file = "", headerFunction = eLaTeXHeader.tabular,
                         footerFunction = eLaTeXFooter.tabular, caption = "", ...) {
  x <- x$latex
  x[is.na(x)] <- na.print
  cat(paste(headerFunction(x, caption, ...), collapse = "\n"), "\n", file = file)
  cat(paste(apply(x, 1, paste, collapse = "&"), collapse = "\\\\\n"), "\\\\\n", file = file,
      append = TRUE)
  cat(paste(footerFunction(x, caption), collapse = "\n"), "\n", file = file, append = TRUE)

}

eLaTeXHeader.tabular <- function(x, caption, collabel.just) {
  if(missing(collabel.just))
    collabel.just <- paste(c("l", rep("c", ncol(x) - 1)), collapse = "")
  
  c("\\begin{table}",
    ps("\\begin{tabular}{", collabel.just, "}"),
    c(paste("\\multicolumn{1}{c}{", colnames(x), "}", collapse = "&"), "\\\\"),
    "\\hline\\\\")
}

eLaTeXFooter.tabular <- function(x, caption) {
    c("\\end{tabular}",
      ps("\\caption{", caption , "}"),
      "\\end{table}")
  }


eLaTeXHeader.longtable <- function(x, caption, collabel.just) {
  if(missing(collabel.just))
    collabel.just <- paste(c("l", rep("c", ncol(x) - 1)), collapse = "")
  c(paste("\\begin{longtable}{", collabel.just, "}"),
    paste("\\caption{", caption, "}\\\\"),
    "\\hline\\hline",
    c(paste("\\multicolumn{1}{c}{", colnames(x), "}", collapse = "&"), "\\\\"),
    "\\hline",
    "\\endhead",
    "\\hline")
}

eLaTeXFooter.longtable <- function(x) {
  c("\\hline",
    "\\end{longtable}")
}


attr(erownames, "latex.function") <-  elatexrownames
attr(erownames, "format.function") <- eprintrownames
attr(etest, "latex.function") <- eprintidentity

tmp <- etable(form, data = pead.bl, colname = "rownames",
              summary.function = erownames) +
  etable() +
  etable(subset = hiv == "Positive") +
  etable(subset = hiv == "Negative") +
  etable(summary.function = etest)


latex(tmp)

etable(form, data = pead.bl, colname = "rownames",
       summary.function = erownames) +
  etable() +
  etable(subset = hiv == "Positive") +
  etable(subset = hiv == "Negative") +
  etable(summary.function = etest) +
  etable(elm, update(form, diffs ~ .), data = pead.bl)


tab1 <- etable(form, data = pead.bl, colname = "rownames",
              summary.function = erownames) +
  etable() +
  etable(subset = hiv == "Positive") +
  etable(subset = hiv == "Negative") +
  etable(summary.function = etest)

  latex(tab1)
