################################################################################
#   Program Name:     mutable.R
#   Author:           Erik Iverson
#   Created:          06/22/2010
#
#   Last saved
#    Time-stamp:      <2011-02-22 12:55:42 eriki>
#
#   ** Generated by auto-insert on 06/22/2010 at 09:49:47**
################################################################################

generateRowNames <- function(var, ...) {
  UseMethod("generateRowNames")
}

generateRowNames.default <- function(var, varName , ...) {
  varName
}

generateRowNames.factor <- function(var, varName, ...) {
  c(varName, paste(varName, names(table(var)), sep = ""))
}

muInsertRow <- function(mat, row, after) {
  if(length(row) == 1)
    row <- c(row, rep("", times = ncol(mat) - 1))
  
  if(after >= 1) 
  rbind(mat[1:after, ],
        row,
        mat[(after+1):nrow(mat),])
  else
    rbind(row, mat)
}

mutable <- function(x, ...) {
  if(missing(x))
    x <- NULL 
  UseMethod("mutable", x)
}

mutable.function <- function(x, ...) {
  do.call(x, list(...))
}

`+.mutable` <- function(x, y) {
  if(!is.null(attr(y, "resolve")) && attr(y, "resolve")) {
    if(is.null(y$data))
      y$data <- x$data
    if(is.symbol(y$data))
      y$data <- eval(y$data)
    if(is.null(y$formula))
      y$formula <- x$formula
    if("subset" %in% names(y)) {
      y$data <- y$data[eval(y$subset, y$data),]
      y$subset <- NULL
    }
    if(is.null(y$markup.list))
      y$markup.list <- x$markup.list
    y <- do.call(mutable.formula, y)
  }
  addelement <- function(x, y) {
    if(!is.matrix(y))
      y <- as.matrix(y)
    un <- union(rownames(x), rownames(y))
    xx <- as.data.frame(unclass(as.matrix(x)))
    yy <- as.data.frame(unclass(as.matrix(y)))
    xx[[".rns"]] <- rownames(x)
    yy[[".rns"]] <- rownames(y)
    mydf <- merge(xx, yy, by = ".rns", all = TRUE)
    mydf <- mydf[match(un, mydf[[".rns"]]), ]
    rns <- mydf[[".rns"]]
    ret <- as.matrix(mydf[!names(mydf) %in% ".rns"])
    rownames(ret) <- rns
    ret
  }
  mapvars.x <- setdiff(names(x), c("formula", "data", "markup.list"))
  mapvars.y <- setdiff(names(y), c("formula", "data", "markup.list"))
  
  if((length(mapvars.x) != length(mapvars.y)) || (any(sort(mapvars.x) != sort(mapvars.y))))
    stop(paste("There are different markup elements in the tables. The left-hand table contains
markup for (", paste(mapvars.x, collapse = " "), ").",
               "The right-hand table contains markup for (",
               paste(mapvars.y, collapse = " "), ").
To combine two tables, they must contain the same markup elements.",
               collapse = " "))
  
  ret <- mapply(addelement, x[mapvars.x], y[mapvars.x], SIMPLIFY = FALSE)
  ret$formula <- x$formula
  ret$data <- x$data
  ret$markup.list <- x$markup.list
  attr(ret, "resolve") <- FALSE
  class(ret) <- c("mutable")
  ret
}

mutable.default <- function(x, ...) {
  m <- as.list(match.call())[-1]
  if(!"data" %in% names(m))
    lst <- c(list(formula = NULL, data = NULL), m)
  else
    lst <- c(list(formula = NULL), m)
  attr(lst, "resolve") <- TRUE
  lst
}

mutable.formula <- function(formula, data,
                            summary.function,
                            markup.list, 
                            post.summary.hook,
                            post.markup.hook, 
                            colname,
                            subset,
                            na.action,
                            ...) {

  ## if there was no data argument, we have to go find it first return
  ## from function knowing this, and resolve the data argument later,
  ## since we know `+.mutable.` must have been called. 
  
  if(missing(data) || missing(markup.list)) {
    lst <- as.list(match.call()[-1])
    attr(lst, "resolve") <- TRUE
    return(lst)
  }

  mf.call <- match.call(expand.dots = FALSE)
  m <- match(c("formula", "data", "subset", "na.action"), names(mf.call), 0L)
  mf.call <- mf.call[c(1L, m)]

  if(missing(na.action))
    mf.call$na.action <- na.pass
  
  mf.call[[1L]] <- as.name("model.frame")
  mf <- eval(mf.call, parent.frame())

  Terms <- terms(formula)
  strat <- attr(Terms, "response")

  if(strat != 0)
    df.vars <- mf[-strat]                 #drop arg?
  else {
    df.vars <- mf
    mf$fake.strat <- gl(1, nrow(mf), labels = "")
    strat <- match("fake.strat", names(mf)) 
  }

  dfv <- list(vars = df.vars, strat = mf[[strat]])

  internalRowNames <- unlist(mapply(generateRowNames, dfv$vars,
                                    names(dfv$vars)))
  
  ret <- lapply(dfv$vars, summary.function, dfv$strat, data, ...)

  if(!missing(post.summary.hook))
    ret <- post.summary.hook(ret)
  
  markupFunction <- function(mf) {
    markup.ret <- NULL
    for(i in 1:length(ret)) {
      val <- mf(ret[[i]], names(ret)[i], data, colname = colname)
      markup.ret <- c(markup.ret, val)
    }
    markup.ret <- as.matrix(markup.ret[internalRowNames], ncol = 1)
    rownames(markup.ret) <- internalRowNames
    colnames(markup.ret) <- colname
    markup.ret
  }

  markup <- lapply(markup.list, markupFunction)

  return.list <- c(markup, formula = formula,
                   data = list(data),
                   markup.list = list(markup.list))

  if(!missing(post.markup.hook))
    return.list <- post.markup.hook(return.list, ret, ...)
  
  attr(return.list, "resolve") <- FALSE
  class(return.list) <- c("mutable")
  return.list
}

print.mutable <- function(x, quote = FALSE, na.print = "--", print.rownames = FALSE, ...) {
  x <- x[["plain"]]
  if(!print.rownames)
    rownames(x) <- NULL
  print.default(unclass(x), quote = quote, na.print = na.print, ...)
}

muPrintIdentity <- function(x, name, data, ...) {
  ret <- x
  names(ret) <- name
  ret
}

muFormatPvalue <- function(x, name, data, threshold = 0.0001, ...) {
  val <- ifelse(x$pvalue < threshold, paste("<", threshold), x$pvalue)
  names(val) <- name
  val
}
