################################################################################
#   Program Name:     mutable.R
#   Author:           Erik Iverson
#   Created:          06/22/2010
#
#   Last saved
#    Time-stamp:      <2010-10-25 22:04:19 erik>
#
#   ** Generated by auto-insert on 06/22/2010 at 09:49:47**
################################################################################

muInsertRow <- function(mat, row, after) {
  if(length(row) == 1)
    row <- c(row, rep("", times = ncol(mat) - 1))
  
  if(after >= 1) 
  rbind(mat[1:after, ],
        row,
        mat[(after+1):nrow(mat),])
  else
    rbind(row, mat)
}

mutable <- function(x, ...) {
  if(missing(x))
    x <- NULL 
  UseMethod("mutable", x)
}

mutable.function <- function(x, ...) {
  do.call(x, list(...))
}

muStratSummary <- function(x, strat, data, ...) {
  UseMethod("muStratSummary")
}
 
muStratSummary.default <- function(x, strat, data, ...) {
  quant <- quantile(x, probs = c(.25, .5, .75), na.rm = TRUE, ...)
  attr(quant, "N") <- length(x)
  quant
}

muStratSummary.factor <- function(x, strat, data, ...) {
  tbl <- table(x, ...)
  attr(tbl, "N") <- length(x)
  tbl
}

`+.mutable` <- function(x, y) {
  if(!is.null(attr(y, "resolve")) && attr(y, "resolve")) {
    if(is.null(y$data))
      y$data <- x$data
    if(is.symbol(y$data))
      y$data <- eval(y$data)
    if(is.null(y$formula))
      y$formula <- x$formula
    if("subset" %in% names(y)) {
      y$data <- y$data[eval(y$subset, y$data),]
      y$subset <- NULL
    }
    y <- do.call(mutable.formula, y)
  }
  addelement <- function(x, y) {
    if(!is.matrix(y))
      y <- as.matrix(y)
    un <- union(rownames(x), rownames(y))
    xx <- as.data.frame(unclass(as.matrix(x)))
    yy <- as.data.frame(unclass(as.matrix(y)))
    xx[[".rns"]] <- rownames(x)
    yy[[".rns"]] <- rownames(y)
    mydf <- merge(xx, yy, by = ".rns", all = TRUE)
    mydf <- mydf[match(un, mydf[[".rns"]]), ]
    rns <- mydf[[".rns"]]
    ret <- as.matrix(mydf[!names(mydf) %in% ".rns"])
    rownames(ret) <- rns
    ret
  }
  mapvars <- c("plain", "latex", "html")
  ret <- mapply(addelement, x[mapvars], y[mapvars], SIMPLIFY = FALSE)
  ret$formula <- x$formula
  ret$data <- x$data
  attr(ret, "resolve") <- FALSE
  class(ret) <- c("mutable")
  ret
}

mutable.default <- function(x, ...) {
  m <- as.list(match.call())[-1]
  if(!"data" %in% names(m))
    lst <- c(list(formula = NULL, data = NULL), m)
  else
    lst <- c(list(formula = NULL), m)
  attr(lst, "resolve") <- TRUE
  lst
}

mutable.formula <- function(formula, data,
                            summary.function = muStratSummary,
                            markupList = list(plain = muStratPlain,
                              latex = muStratLatex,
                              html = muStratHTML),
                            post.summary.hook,
                            post.markup.hook, 
                            colname,
                            subset, ...) {

  ## if there was no data argument, we have to go find it first return
  ## from function knowing this, and resolve the data argument later,
  ## since we know `+.mutable.` must have been called. 
  
  if(missing(data)) {
    lst <- as.list(match.call()[-1])
    attr(lst, "resolve") <- TRUE
    return(lst)
  }

  mf.call <- match.call(expand.dots = FALSE)
  m <- match(c("formula", "data", "subset", "na.action"), names(mf.call), 0L)
  mf.call <- mf.call[c(1L, m)]
  mf.call[[1L]] <- as.name("model.frame")
  mf <- eval(mf.call, parent.frame())

  Terms <- terms(formula)
  strat <- attr(Terms, "response")

  if(strat != 0)
    df.vars <- mf[-strat]                 #drop arg?
  else {
    df.vars <- mf
    mf$fake.strat <- gl(1, nrow(mf), labels = "")
    strat <- match("fake.strat", names(mf)) 
  }

  dfv <- list(vars = df.vars, strat = mf[[strat]])

  table.vars <- strsplit(tail(as.character(formula), n = 1), " + ", fixed = TRUE)[[1]]

  xx <- NULL
  for(x in table.vars) {
      if(is.numeric(data[[x]])) {
        y <- x
      }
      if(is.factor(data[[x]])) {
        y <- c(x, paste(x, names(table(data[[x]])), sep = ""))
      }
      xx <- c(xx, y)
  }
  
  ret <- lapply(dfv$vars, summary.function, dfv$strat, data, ...)

  ## apply an arbitrary hook function

  if(!missing(post.summary.hook))
    ret <- post.summary.hook(ret)
  
  ## grab any defaults for formatting functions from the
  ## summary.function attributes we need to know which ones to grab
  ## though, probably through a list as as argument to this function.
  ## Or, we could just define any of them based on the attribute being
  ## present.  But how would we know which functions are actually
  ## meant to be called?  Perhaps intitial object can specify these.
  ## for now, just use our latex/html/format

  ## if(!is.null(lf <- attr(summary.function, "latex.function")))
  ##   latex.function <- lf
  ## if(!is.null(hf <- attr(summary.function, "html.function")))
  ##   html.function <- hf
  ## if(!is.null(ff <- attr(summary.function, "plain.function")))
  ##   plain.function <- ff

  markupFunction <- function(mf) {
    markup.ret <- NULL
    for(i in 1:length(ret)) {
      val <- mf(ret[[i]], names(ret)[i], data, colname = colname)
      markup.ret <- c(markup.ret, val)
    }
    markup.ret <- as.matrix(markup.ret[xx], ncol = 1)
    rownames(markup.ret) <- xx
    colnames(markup.ret) <- colname
    markup.ret
  }

  markup <- lapply(markupList, markupFunction)

  return.list <- c(markup, formula = formula, data = list(data))

  if(!missing(post.markup.hook))
    return.list <- post.markup.hook(return.list, ret, ...)
  
  attr(return.list, "resolve") <- FALSE
  class(return.list) <- c("mutable")
  return.list
}

print.mutable <- function(x, quote = FALSE, na.print = "--", print.rownames = FALSE, ...) {
  x <- x[["plain"]]
  if(!print.rownames)
    rownames(x) <- NULL
  print.default(unclass(x), quote = quote, na.print = na.print, ...)
}

muPrintIdentity <- function(x, name, data, ...) {
  ret <- x
  names(ret) <- name
  ret
}

muRownamesSummary <- function(x, ...) {
  UseMethod("muRownamesSummary")
}

muRownamesSummary.default <- function(x, ...) {
  label(x)
}

muRownamesSummary.factor <- function(x, ...) {
  ret <- c(label(x), levels(x))
  class(ret) <- "rowFactor"
  ret
}

muResponseSummary <- function(x, strat, data, ...) {
  UseMethod("muResponseSummary")
}
 
muResponseSummary.default <- function(x, strat, data, ...) {
  ct <- cor.test(x, strat)
  c(ct$estimate, ct$conf.int)
}

muResponseSummary.factor <- function(x, strat, data, ...) {
  ta <- tapply(strat, x, quantile, probs = c(.25, .5, .75))
  class(ta) <-  "muResponseSummaryFactor"
  ta
}

