################################################################################
#   Program Name:     themes.R
#   Author:           Erik
#   Created:          06/23/2012
#
#   Last saved
#    Time-stamp:      <2012-07-13 22:43:30 erik>
#
#   Purpose:          
#
#   Input:            
#
#   Output:           
#
#   NB:               
#
#   Modfied by:       
#
#   ** Generated by auto-insert on 06/23/2012 at 13:26:08**
################################################################################

theme_default <- function() {

}
                           
